<script setup>
import {ref,onMounted} from 'vue';
const user=ref(null),username=ref(''),password=ref(''),registering=ref(false),bases=ref([]),active=ref(''),newName=ref(''),documents=ref([]),graph=ref([]),history=ref([]),progress=ref({mastery:[],mistakes:[],path:[]}),quizzes=ref([]),results=ref({}),selections=ref({}),file=ref(null),question=ref(''),mode=ref('auto'),generate=ref(true),answer=ref(null),tab=ref('问答'),status=ref(''),busy=ref(false),health=ref({});
let generation=0;
async function api(path,body,method){const opt={method:method||(body===undefined?'GET':'POST'),credentials:'same-origin',headers:{}};if(body instanceof FormData)opt.body=body;else if(body!==undefined){opt.body=JSON.stringify(body);opt.headers['Content-Type']='application/json';}const r=await fetch(path,opt),d=await r.json();if(!r.ok){if(r.status===401)user.value=null;throw new Error(typeof d.detail==='string'?d.detail:'请求参数无效，请检查输入');}return d;}
async function task(fn){if(busy.value)return;busy.value=true;status.value='正在处理…';try{await fn();}catch(e){status.value=e.message;}finally{busy.value=false;}}
const path=()=>`/api/bases/${active.value}`;
async function refresh(){if(!active.value)return;const id=active.value,v=++generation;const[d,g,h,p]=await Promise.all([api(path()+'/documents'),api(path()+'/graph'),api(path()+'/history'),api(path()+'/progress')]);if(id!==active.value||v!==generation)return;documents.value=d;graph.value=g;history.value=h;progress.value=p;}
async function selectBase(){answer.value=null;quizzes.value=[];results.value={};selections.value={};await refresh();status.value='知识库已加载';}
async function load(){bases.value=await api('/api/bases');if(!bases.value.some(b=>b.id===active.value))active.value=bases.value[0]?.id||'';await refresh();}
async function login(){await task(async()=>{if(registering.value)await api('/api/auth/register',{username:username.value,password:password.value});await api('/api/auth/login',{username:username.value,password:password.value});password.value='';user.value=await api('/api/auth/me');await load();status.value='先建立知识库，再上传资料';});}
async function logout(){await task(async()=>{await api('/api/auth/logout',{});user.value=null;registering.value=false;password.value='';active.value='';bases.value=[];documents.value=[];graph.value=[];history.value=[];answer.value=null;quizzes.value=[];results.value={};selections.value={};progress.value={mastery:[],mistakes:[],path:[]};status.value='已退出';});}
async function createBase(){await task(async()=>{const b=await api('/api/bases',{name:newName.value});newName.value='';active.value=b.id;await load();await selectBase();});}
async function upload(){await task(async()=>{if(!file.value)throw new Error('请先选择资料');if(file.value.size>3*1024*1024)throw new Error('文件不能超过 3 MiB');const body=new FormData();body.append('file',file.value);const r=await api(path()+'/documents',body);await refresh();status.value=r.duplicate?'资料已经存在':`入库完成：${r.chunks} 个片段`;});}
async function removeDocument(d){if(!confirm(`删除“${d.name}”？相关练习和问答历史也会清理。`))return;await task(async()=>{await api(path()+'/documents/'+d.id,undefined,'DELETE');answer.value=null;quizzes.value=[];results.value={};await refresh();status.value='资料及相关记录已清理';});}
async function indexVectors(){await task(async()=>{const r=await api(path()+'/index',{});status.value=`已建立 ${r.indexed} 条语义索引`;});}
async function ask(){await task(async()=>{answer.value=await api(path()+'/ask',{question:question.value,mode:mode.value,generate:generate.value});await refresh();status.value=answer.value.warning||`找到 ${answer.value.sources.length} 条证据`;});}
async function quiz(){await task(async()=>{quizzes.value=await api(path()+'/quizzes',{count:5});results.value={};selections.value={};status.value=`已生成 ${quizzes.value.length} 道练习`;});}
async function grade(q){await task(async()=>{if(selections.value[q.id]===undefined)throw new Error('请先选择答案');results.value[q.id]=await api(path()+'/quizzes/'+q.id+'/submit',{selected:Number(selections.value[q.id])});await refresh();status.value='批改完成';});}
onMounted(async()=>{try{health.value=await api('/api/health');user.value=await api('/api/auth/me');await load();}catch(e){status.value=e.message;}});
</script>
<template>
<header><div class="brand"><span class="logo">知</span><div><h1>智学</h1><p>学习有依据，成长有方向</p></div></div><div class="right"><span class="pill">{{health.chat_model_configured?'模型已配置':'离线证据模式'}}</span><button v-if="user" class="secondary" :disabled="busy" @click="logout">{{user.username}} · 退出</button></div></header>
<main v-if="!user" class="login"><section><span class="eyebrow">YOUR PERSONAL LEARNING SPACE</span><h2>把资料变成<br>自己的知识体系</h2><p class="muted">上传课程资料，查找原文依据，练习知识关系，追踪薄弱知识点。</p><div class="features"><span>01 · 资料入库</span><span>02 · 有据问答</span><span>03 · 练习复盘</span></div></section><form class="panel" @submit.prevent="login"><h3>{{registering?'建立学习账号':'进入学习空间'}}</h3><label>用户名<input v-model="username" required minlength="3" maxlength="32" pattern="[a-zA-Z0-9_]+" autocomplete="username" placeholder="3–32 位字母、数字或下划线"></label><label>密码<input v-model="password" type="password" required minlength="10" maxlength="128" :autocomplete="registering?'new-password':'current-password'" placeholder="至少 10 个字符"></label><button class="full" :disabled="busy">{{registering?'注册并登录':'登录'}}</button><button class="link full" type="button" :disabled="busy" @click="registering=!registering">{{registering?'返回登录':'首次使用？创建账号'}}</button><p class="status" role="status">{{status}}</p></form></main>
<main v-else class="workspace"><aside class="panel"><h3>我的知识库</h3><select v-model="active" :disabled="busy" @change="()=>task(selectBase)"><option value="" disabled>请选择知识库</option><option v-for="b in bases" :key="b.id" :value="b.id">{{b.name}}</option></select><form class="create" @submit.prevent="createBase"><input v-model="newName" required maxlength="80" placeholder="新建课程知识库"><button :disabled="busy">＋</button></form><template v-if="active"><h3>学习资料</h3><p class="hint">TXT / MD / PDF / DOCX / PPTX；图片需启用 OCR。每份最多 3 MiB。</p><input type="file" accept=".txt,.md,.pdf,.docx,.pptx,.png,.jpg,.jpeg" :disabled="busy" @change="file=$event.target.files[0]"><button class="full" :disabled="busy" @click="upload">上传并建立索引</button><button class="secondary full" :disabled="busy||!health.embedding_model_configured" @click="indexVectors">更新语义索引</button><ul><li v-for="d in documents" :key="d.id"><div><strong>{{d.name}}</strong><small>{{d.chunks}} 个片段</small></div><button class="link" :disabled="busy" @click="removeDocument(d)">删除</button></li></ul><p v-if="!documents.length" class="hint">可上传 datasets 中的示例资料。</p></template></aside>
<section><span class="eyebrow">LEARNING WORKSPACE</span><h2>理解、练习，再向前一步</h2><nav><button v-for="t in ['问答','知识关系','练习','学习记录']" :key="t" :class="{selected:tab===t}" @click="tab=t">{{t}}</button></nav><p class="status" role="status" aria-live="polite">{{status}}</p><div v-if="!active" class="panel empty">先在左侧建立一个知识库。</div>
<template v-else-if="tab==='问答'"><form class="panel" @submit.prevent="ask"><label>你想了解什么？<textarea v-model="question" required maxlength="1000" placeholder="例如：学习率如何影响梯度下降？"></textarea></label><div class="toolbar"><select v-model="mode"><option value="auto">自动路由</option><option value="hybrid">混合检索</option><option value="bm25">BM25 关键词</option><option value="cosine">词频余弦</option><option value="graph">关系增强</option><option value="semantic">语义向量</option></select><label class="check"><input v-model="generate" type="checkbox">模型生成（需配置）</label><button :disabled="busy">检索并回答</button></div></form><article v-if="answer" class="panel"><div class="toolbar"><h3>{{answer.answer_kind==='generated'?'学习助手的回答':'资料中的原文证据'}}</h3><span class="pill">{{answer.mode}}</span></div><p class="pre">{{answer.answer}}</p><p class="hint">引用编号可帮助核对来源，但不能保证回答事实正确。</p></article><details v-for="(s,i) in answer?.sources||[]" :key="s.chunk_id" class="panel source" open><summary>[{{i+1}}] {{s.name}} · 第 {{s.page}} 页</summary><p class="pre">{{s.text}}</p><small>片段 {{s.chunk_id}} · 分数 {{Number(s.score).toFixed(4)}}</small></details></template>
<template v-else-if="tab==='知识关系'"><article class="panel"><h3>资料中的显式关系</h3><p class="hint">读取“关系：实体|关系|实体”行，不自动推断知识关系。</p><div v-for="(e,i) in graph" :key="i" class="edge"><strong>{{e.subject}}</strong><span>{{e.predicate}} →</span><strong>{{e.object}}</strong><small>{{e.chunk_id}}</small></div><p v-if="!graph.length" class="hint">暂无关系，请上传示例。</p></article></template>
<template v-else-if="tab==='练习'"><article class="panel"><h3>从资料出发，检查掌握程度</h3><p class="hint">基于显式关系生成选择题；每道题首次提交计入统计。</p><button :disabled="busy" @click="quiz">生成 5 道练习</button></article><article v-for="(q,i) in quizzes" :key="q.id" class="panel"><h3>{{i+1}}. {{q.stem}}</h3><label v-for="(o,j) in q.options" :key="j" class="option"><input v-model="selections[q.id]" type="radio" :name="q.id" :value="j" :disabled="Boolean(results[q.id])">{{String.fromCharCode(65+j)}}. {{o}}</label><button :disabled="busy||Boolean(results[q.id])" @click="grade(q)">提交答案</button><div v-if="results[q.id]" class="feedback"><strong>{{results[q.id].correct?'回答正确':'需要再复习'}} · 正确选项 {{String.fromCharCode(65+results[q.id].answer)}}</strong><p>{{results[q.id].explanation}}</p><small>依据片段：{{results[q.id].source}}</small></div></article></template>
<template v-else><div class="stats"><article class="panel"><small>知识点</small><strong>{{progress.mastery.length}}</strong></article><article class="panel"><small>错题记录</small><strong>{{progress.mistakes.length}}</strong></article><article class="panel"><small>问答记录</small><strong>{{history.length}}</strong></article></div><article class="panel"><h3>建议复习顺序</h3><p class="hint">掌握度根据已完成练习估计，少量练习结果仅供复习参考。</p><div v-for="(item,i) in progress.path" :key="item.topic" class="path"><span>{{i+1}}</span><div><strong>{{item.topic}}</strong><p>{{item.reason}} · {{item.attempts}} 次练习</p></div><span>{{Math.round(item.mastery*100)}}%</span></div><p v-if="!progress.path.length" class="hint">先上传资料并完成练习。</p></article><article class="panel"><h3>错题本</h3><details v-for="q in progress.mistakes" :key="q.id"><summary>{{q.stem}}</summary><p>正确答案：{{q.options[q.answer]}}</p><p>{{q.explanation}}</p></details></article><article class="panel"><h3>问答历史</h3><details v-for="h in history" :key="h.id"><summary>{{h.question}}</summary><p class="pre">{{h.result.answer}}</p><small>{{new Date(h.created*1000).toLocaleString()}}</small></details></article></template>
</section></main><footer>智学 v0.2 · 课程资料由用户提供 · 本地模型可选 · 基础学习统计</footer>
</template>
